name: Run Unit Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install dependencies
        run: |
          set -ex
          sudo apt-get -y update
          sudo apt-get -y install ccache cmake make build-essential

      - name: Configure CMake
        run: |
          mkdir -p /home/runner/work/reactive/reactive/build/rootfs
          cmake -B ${{github.workspace}}/build

      - name: Build Test Binaries
        run: |
          make -C ${{github.workspace}}/build

      - name: Run Tests
        run: |
          CTEST_OUTPUT_ON_FAILURE=On ctest -V --test-dir ${{github.workspace}}/build --output-junit ${{github.workspace}}/build/test-results.xml || true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: ${{github.workspace}}/build/test-results.xml
          check_name: Reactive Test Results
